IVH7A4Cinema/IVH7A4Cinema.WebUI/Controllers/FilmController.cs
using IVH7A4Cinema.Domain.Abstract;
using IVH7A4Cinema.Domain.Entities;
using IVH7A4Cinema.WebUI.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IVH7A4Cinema.WebUI.Controllers
{
    public class FilmController : Controller
    {
        private IFilmRepository repository;
        private IReservationRepository reservationRepository;
        private IRoomRepository roomRepository;

        public FilmController(IRoomRepository roomRepository, IFilmRepository filmRepository, IReservationRepository reservationRepository)
        {
            this.repository = filmRepository;
            this.reservationRepository = reservationRepository;
            this.roomRepository = roomRepository;
        }

        public ViewResult SchedulePlanning()
        {
            var schedules = repository.Schedules;
            IEnumerable<Film> filmsToday = repository.Films
                .Join(schedules, f => f.FilmID, s => s.FilmID, (f, s) => new { Film = f, Schedule = s })
                .Where(s => s.Schedule.Date == DateTime.Now.Date)                
                .GroupBy(film => film.Film.Name,(key, film) => film.FirstOrDefault())
                .Select(fg => new Film { FilmID = fg.Film.FilmID, Name = fg.Film.Name,
                Description = fg.Film.Description, Director = fg.Film.Director,
                Language = fg.Film.Language, length = fg.Film.length, Type = fg.Film.Type,
                Trailer = fg.Film.Trailer, Age = fg.Film.Age, SubTitles = fg.Film.SubTitles})
                .Distinct()
                .ToList();

            FilmListViewModel model = new FilmListViewModel
            {
                Films = filmsToday
            };

            return View(model);
        }
        [ExcludeFromCodeCoverage]
        public PartialViewResult FilmSchedulePlanning(Film Film)
        {
            try
            {
                Schedule schedule = repository.Schedules
                    .Where(s => s.Date == DateTime.Now.Date && s.FilmID == Film.FilmID && s.Time > DateTime.Now.TimeOfDay)
                    .OrderBy(s => s.Time).First();


            FilmScheduleModel model = new FilmScheduleModel
            {
                Film = Film,
                Schedule = schedule,
                Room = roomRepository.Rooms.Where(r => r.RoomNumber == schedule.RoomID).FirstOrDefault()
            };

            return PartialView(model);
            }
            catch (Exception ex)
            { }
            return null;
        }
        [ExcludeFromCodeCoverage]
        public PartialViewResult Schedule(int FilmID, Schedule Schedule, Room Room)
        {
            IEnumerable<Schedule> schedules = repository.Schedules
                .Where(s => s.Date == DateTime.Now.Date && s.FilmID == FilmID && s.Time > DateTime.Now.TimeOfDay)
                .OrderBy(s => s.Time);
            return PartialView(schedules);
        }
    }
}

IVH7A4Cinema/IVH7A4Cinema.WebUI/Views/Shared/FilmSchedulePlanning.cshtml
@model IVH7A4Cinema.WebUI.Models.FilmScheduleModel

<div class="col-md-6">
    <div class="col-md-12">
        <h2>@Model.Film.Name</h2>
    </div>

    <div class="col-md-12">
        <div class="col-md-5 nopad-lr">
            <table class="scheduleTable">
                <tr>
                    <td>Leeftijd:</td>
                    <td>@Model.Film.Age</td>
                </tr>
                <tr>
                    <td>Duur:</td>
                    <td>@Model.Film.length minuten</td>
                </tr>
                <tr>
                    <td>Taal:</td>
                    <td>@Model.Film.Language</td>
                </tr>
                <tr>
                    <td>Ondertitels:</td>
                    <td>@Model.Film.SubTitles</td>
                </tr>
                <tr>
                    <td>3D:</td>
                    <td>
                        @if (Model.Film.Type == "3D")
                    {
                        @:Ja
                        }
                    else {
                        @:Nee
                        }
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-7">
        @Html.Action("Schedule", "Film", new { FilmID = Model.Film.FilmID, Schedule = Model.Schedule, Room = Model.Room })
    </div>
</div>
</div>

IVH7A4Cinema/IVH7A4Cinema.WebUI/Views/Shared/PaymentCheck.cshtml
@{
    ViewBag.Title = "PIN Betaling";

}

<div align="center">
    <h1>@ViewBag.PaymentMsg</h1>
    <h2>Over 5 seconden wordt u naar het hoofdscherm gebracht.</h2>

</div>

IVH7A4Cinema/IVH7A4Cinema.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title> 
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Content/js/Site.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Hoofdmenu", "Index", "Home", new { area = "" }, new { @class = "btn btn-block btn-default btn-lg" })
            </div>
            <div class="text-center">
                <h1>@ViewBag.Title</h1>
                <div class="pull-right real_time">
                    <span id="real_time">

                    </span>
                </div>
            </div>

            
            
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>


</body>
</html>